default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: stock_app_development

test:
  <<: *default
  database: stock_app_test

production:
  <<: *default
  database: stock_app_production
  host: <%= ENV['PG_HOST'] %> 
  username: <%= ENV['PG_USERNAME'] %>
  passwrod: <%= ENV['PG_PASSWORD'] %>